# Generated by Django 4.2.6 on 2024-01-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PembeliGo_Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NO_ANTREAN', models.IntegerField(null=True)),
                ('Nama', models.CharField(max_length=255)),
                ('PESANAN', models.TextField(max_length=255)),
                ('Jumlah_Makanan', models.IntegerField(null=True)),
                ('Jumlah_Minuman', models.IntegerField(null=True)),
            ],
        ),
    ]
